version: '3'
services:
  parkview-webdriver:
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    networks:
      - parkview
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - parkview-webdriver
    depends_on:
      - parkview-webdriver
    ports:
      - "1337:8080"
    command: ["--selenoid-uri", "http://parkview-webdriver:4444"]
    networks:
      - parkview

  parkview-backend:
    command:
      - --parkview.database.embedded=true
      - --parkview.git-api.owner=pse-parkview
      - --parkview.git-api.repoName=ginkgo
      - --parkview.git-api.firstCommitSha=3eca4d1c25cb04a084dd77c6e8c273da9603e17f
      - --parkview.git-api.token=${GIT_TOKEN}
      - --parkview.git-api.username=${GIT_USERNAME}

  parkview-postgres:
    restart: "no"
    entrypoint: ["echo", "Service foo disabled"]
  pgadmin-parkview:
    restart: "no"
    entrypoint: ["echo", "Service foo disabled"]

networks:
  parkview:
