name: Build and Push Containers Nightly

on:
  push:
    branches:
      - develop
      
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: Implementation/backend/
          push: true
          tags: tadachs/parkview-backend:nightly
          
      
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: Implementation/frontend/
          push: true
          tags: tadachs/parkview-frontend:nightly
          
      - name: Deploy to demo server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_SERVER_HOST }}
          username: ${{ secrets.DEMO_SERVER_USER }}
          password: ${{ secrets.DEMO_SERVER_PASSWORD }}
          script: ${{ secrets.DEMO_SERVER_SCRIPT }}
