
name: Integration Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - quality-assurance

  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2    
    
    - name: Get IP Address
      run: echo "##[set-output name=ip;]$(hostname -I | awk '{print $1}')"
      id: ip_addr 
    
    - uses: nanasess/setup-chromedriver@master
      
    - name: Setup Pyhon
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: QualityAssurance/integration_tests/requirements.txt

    - name: Run Tests
      working-directory: QualityAssurance/integration_tests/
      run: python3 main.py --backend http://localhost:8080/parkview --frontend http://${{ steps.ip_addr.outputs.ip }}:4200 --github-token ${{ secrets.OAUTH_TOKEN }} --github-user ${{ secrets.OAUTH_USER }}
