
name: Integration Tests

on:
  push:
    branches: 
      - main
      - develop
      - quality-assurance
  pull_request:
    branches:
      - main
      - develop
      - quality-assurance

  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2    
    
    - name: Install something so I can use the clipboard
      run: sudo apt-get install xorg openbox xclip xsel
    
    - name: I hope this works
      run: startx
    
    - name: Setup Chrome
      uses: nanasess/setup-chromedriver@master
      
    - name: Setup Pyhon
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: QualityAssurance/integration_tests/requirements.txt

    - name: Run Tests
      working-directory: QualityAssurance/integration_tests/
      run: python3 main.py --backend http://localhost:8080/parkview --frontend http://0.0.0.0:4200 --github-token ${{ secrets.OAUTH_TOKEN }} --github-user ${{ secrets.OAUTH_USER }} --timeout 60
