
name: Integration Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - quality-assurance

  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444
        options: --shm-size="2g"


    steps:
    - uses: actions/checkout@v2
    - run: ifconfig
    - name: Get IP Address
      run: echo "##[set-output name=ip;]$(ifconfig eth0 | grep 'inet [0-9\.]* ' -o | sed 's/[^0-9\.]//g')"
      id: ip_addr 
      
    - name: Setup Pyhon
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: QualityAssurance/integration_tests/requirements.txt

    - name: Run Tests
      working-directory: QualityAssurance/integration_tests/
      run: python3 main.py --backend http://localhost:8080/parkview --frontend http://${{ steps.ip_addr.ouputs.ip }}:4200 --selenium http://localhost:4444/wd/hub --github-token ${{ secrets.OAUTH_TOKEN }} --github-user ${{ secrets.OAUTH_USER }}
