name: Test Backend

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Test with Gradle
        run: ./gradlew test
        working-directory: Implementation/backend/

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        id: extract_branch
        
      - name: Generate Jacoco Badge
        uses: cicirello/jacoco-badge-generator@v2
        id: jacoco
        with:
          jacoco-csv-file: Implementation/backend/build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: false
          generate-coverage-badge: false
      
      - name: Calculate percentage
        id: calc
        shell: bash
        run: |
          echo "##[set-output name=percent;]$(echo "${{ steps.jacoco.outputs.coverage }} * 100" | bc)"
          
      - name: Generate Coverage Badge
        uses: taDachs/stupid-coverage-badge-generator@initial
        with:
          percent: ${{ steps.calc.outputs.percentage }}
          text: ${{ steps.extract_branch.outputs.branch }}-coverage backend
          output-path: ./
          
      - name: Upload Badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.BADGES_GIST_SECRET }}
          gist_id: 2f350a3c58fed9515b658495edc70191
          gist_file_name: parkview_${{ steps.extract_branch.outputs.branch }}_coverage.svg
          file_path: ./badge.svg
